### ISSUE TITLE
Github Actions failing on large_data.Rmd re-building with the message "Killed"

### ISSUE THREAD

**Issue by drisso** [Bioconductor/ISMB.OSCA#9]
See here:
https://github.com/Bioconductor/ISMB.OSCA/actions/runs/5215979592/jobs/9414197334

@LiNk-NY any idea what's going on?

**Comment by LiNk-NY** [comment]
We might be hitting the time limit on GHA. I will take a look at the configurations.

**Comment by LiNk-NY** [comment]
It seems like it's a large_data issue? The runners have a max of 7 GB of memory but running the vignette locally maxes out at 2 GB based on my RStudio mem monitor.

**Comment by drisso** [comment]
Any chance we can set eval=FALSE in parts of the large_data vignette until this is solved? In the end, we will run the workshop on workshop.bioconductor.org so I don't think that this is critical, we just need this to create the container and have a rendered version of the vignettes.

**Comment by lgeistlinger** [comment]
The large data vignette on it's own is not hitting the memory limits as it compiled fine in 2323695 and has not been changed since then. As all vignettes get built by the same R process we are accumulating memory across the vignettes and seem to be hitting the fence eventually with the large data vignette being built last. I'll set some memory intensive chunks to `eval=FALSE` in the large data vignette, but we might need to monitor memory requirements across vignettes going forward and as we add more contents.

**Comment by drisso** [comment]
Mmmm.. this is strange, no?

I would have guessed that each vignette is its own R session. Would then call `rm(list=ls()); gc()` at the beginning of each vignette clean the memory and solve this issue?

**Comment by LiNk-NY** [comment]
It looks to be working okay so far. Thanks for that change. 
I made a few adjustments to the GHA workflows.

**Comment by lgeistlinger** [comment]
Thanks! Looks like we can close this for now, but if we hit that memory limit again it sounds worth trying your suggestion, Davide.

**Comment by drisso** [comment]
Great, thanks!
